name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      #if: env.DOCKERHUB_USERNAME != ''
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata from Dockerfile
      id: metadata
      run: |
        # Extract the image name and version directly from Dockerfile labels
        IMAGE_NAME=$(grep "LABEL org.opencontainers.image.name" docker/Dockerfile | cut -d'"' -f2)
        IMAGE_VERSION=$(grep "LABEL org.opencontainers.image.version" docker/Dockerfile | cut -d'"' -f2)
        
        # Set the extracted variables as environment variables
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "IMAGE_VERSION=${IMAGE_VERSION}" >> $GITHUB_ENV
        
        echo "Image name: ${IMAGE_NAME}"
        echo "Image version: ${IMAGE_VERSION}"

    - name: Build and Push Docker Image to Docker Hub (if DOCKERHUB_USERNAME is set)
      #if: env.DOCKERHUB_USERNAME != ''
      uses: docker/build-push-action@v5
      with:
        context: ./docker
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}:latest

    - name: Build and Push Docker Image to GitHub Container Registry
      uses: docker/build-push-action@v5
      with:
        context: ./docker
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}}
          ghcr.io/${{ github.repository }}/${{env.IMAGE_NAME}}:latest

    - name: Logout from Docker Hub
      #if: env.DOCKERHUB_USERNAME != ''
      run: docker logout
